modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/CodeOfArdonia/TameTools/issues"
license = "All Right Reserved"

[[mods]]
modId = "tame_tools"
version = "${version}"
displayName = "Tame Tools"
authors = "IAFEnvoy, suzuran271954"
description = '''
Additional tools for Tameable Mod
'''
logoFile = "tame_tools.jpg"

[[dependencies.tame_tools]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tame_tools]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tame_tools]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"


[[dependencies.tame_tools]]
modId = "tameable"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"